// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxcwtmyklpeiellhkvuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94Y3d0bXlrbHBlaWVsbGhrdnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Mjg5MDEsImV4cCI6MjA2NjAwNDkwMX0.RUCDA4vPb9MxlOn2p71ixUkKad_H2jy0rvSClF8v7WY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);